services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./install-docker.sh:/install-docker.sh
    environment:
      # Use Unix socket instead of TLS certificates
      - DOCKER_HOST=unix:///var/run/docker.sock
      # Unset these variables to avoid looking for certificates
      - DOCKER_TLS_VERIFY=
      - DOCKER_CERT_PATH=
    # run script to install docker cli in the jenkins container
    entrypoint: ["/bin/bash", "-c", "chmod +x /install-docker.sh && /install-docker.sh && /usr/local/bin/jenkins.sh"]

volumes:
  jenkins_home: